[build]
  base = "packages/web-next"
  command = "npm ci && npm run build"

# Explicitly add Next.js plugin for proper handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build environment variables and secrets scanning configuration
[build.environment]
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_b3V0Z29pbmctbWFydGVuLTI0LmNsZXJrLmFjY291bnRzLmRldiQ"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/edge-functions/**,.github/workflows/**,node_modules/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"

[dev]
  framework = "#static"
  port = 3000
  autoLaunch = false

# API routes are handled by Next.js - no redirects needed

[[redirects]]
  from = "/sign-in"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200


