[build]
  base = "packages/web-next"
  command = "npm ci && npm run build"
  publish = ".next"
  # Auto-deploy from main branch - GitHub Actions removed
  
# Build environment variables and secrets scanning configuration  
[build.environment]
  NODE_VERSION = "22"
  # CLERK ENV TEMPORARILY RESTORED TO FIX BUILD FAILURE
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_b3V0Z29pbmctbWFydGVuLTI0LmNsZXJrLmFjY291bnRzLmRldiQ"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/edge-functions/**,.github/workflows/**,node_modules/**"
  # SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 3000
  autoLaunch = false

# Next.js handles its own routing - no redirects needed

