[build]
  command = "cd packages/web-next && npm ci && npm run build"
  publish = "packages/web-next/.next"
  functions = "netlify/functions"
  environment = { NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_b3V0Z29pbmctbWFydGVuLTI0LmNsZXJrLmFjY291bnRzLmRldiQ" }

# Explicitly add Next.js plugin for proper handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Secrets scanning configuration
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/edge-functions/**,.github/workflows/**,node_modules/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"

[dev]
  framework = "#static"
  port = 3000
  autoLaunch = false

[[redirects]]
  from = "/api/devices/register"
  to = "/.netlify/functions/devices-register"
  status = 200

[[redirects]]
  from = "/api/devices/link"
  to = "/.netlify/functions/devices-link"
  status = 200

[[redirects]]
  from = "/api/devices/exchange"
  to = "/.netlify/functions/devices-exchange"
  status = 200

[[redirects]]
  from = "/api/devices/refresh"
  to = "/.netlify/functions/devices-refresh"
  status = 200

[[redirects]]
  from = "/api/presentations/save"
  to = "/.netlify/functions/presentations-save"
  status = 200

[[redirects]]
  from = "/api/presentations/get"
  to = "/.netlify/functions/presentations-get"
  status = 200

[[redirects]]
  from = "/api/presentations/list"
  to = "/.netlify/functions/presentations-list"
  status = 200

[[redirects]]
  from = "/api/auth/bootstrap"
  to = "/.netlify/functions/auth-bootstrap"
  status = 200

[[redirects]]
  from = "/api/protected/ping"
  to = "/.netlify/functions/protected-ping"
  status = 200

[[redirects]]
  from = "/sign-in"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200


