[meta]
agent = "full-stack-engineer"
updated = 2025-08-20
sprint = "7+ Complete"
role = "Feature Development & Implementation"

[patterns]
# Sprint 6+ success patterns
hooks = "useUser() > localStorage for auth data"
loading = "ClerkLoading/ClerkLoaded eliminates FOUC"
api = "createClerkClient() for server-side user data"
bootstrap = "Real Clerk email → Supabase sync pattern"
validation = "E2E testing before delivery"

[metrics]
# Current implementation metrics
components_delivered = ["Navigation", "Dashboard", "LandingPage"]
typescript_errors = 0
build_status = "clean"
runtime_errors = 0

[tools]
frontend = ["next.js", "react", "typescript", "tailwind"]
backend = ["clerk", "supabase", "netlify-functions"]
testing = ["vitest", "playwright", "console-test.js"]
build = ["vite", "npm", "tsc"]
styleguide = "http://localhost:3000/styleguide"

[lessons]
sprint6 = ["Direct Clerk hooks eliminate complexity", "One component at a time", "Validate after each step"]
sprint5 = ["Never disable TypeScript", "Test imports before use", "Build errors = stop immediately"]

[workflow]
# Mandatory 5-step process
environment = "Kill ports, start clean, verify HTTP 200"
implementation = "Read memory, maintain patterns, TypeScript compliance"
testing = "Unit tests + runtime validation"
quality = "Build + TypeScript + console errors = 0"
documentation = "Update memory with evidence"

[deployment]
# Sprint 7 CI/CD Pipeline (COMPLETED)
production_url = "https://productory-powerups.netlify.app"
deploy_trigger = "Push to main branch → automatic Netlify deployment"
deploy_time = "4-minute cycle"
production_parity = "User validated: identical to localhost:3000"
next_js_config = "Standard build (no standalone) + explicit Netlify plugin"

[ui_system]
# Design system location and capabilities
styleguide_page = "/packages/web-next/src/app/styleguide/page.tsx"
styleguide_url = "http://localhost:3000/styleguide"
components_path = "/packages/shared/ui/"
config = "tailwind.config.js + packages/web/src/globals.css"
validation = "curl -I localhost:3000/styleguide for 200 OK"

# Available components with variants
button = "primary|secondary|outline|destructive|ghost|export|sync-save|sync-load"  
card = "basic|hover|status-specific"
input = "text|email|disabled states"

# Productory Brand Colors (LEARNED 2025-08-19)
productory_colors = "white=#FFFFFF|surface-light=#FFFCFE|surface-tinted=#F6F2F8|purple-1=#491A73|purple-2=#830F70|purple-3=#B50864|grey=#475467"
brand_colors = "primary=#491A73|secondary=#830F70|accent=#B50864|success=#16a34a|destructive=#dc2626"
tailwind_classes = "bg-productory-purple-1|bg-productory-purple-2|bg-productory-purple-3|text-productory-grey"

[next]
tasks = ["Implement presentation CRUD", "Add real-time sync"]
priority = "Maintain 0 errors baseline"