[meta]
agent = "ux-ui-engineer"
updated = 2025-09-05T00:00:00Z
sprint = "6+"
role = "User Experience Design & UI Consistency"

[patterns]
# Sprint 6+ UX patterns
fouc_elimination = "Auth-aware skeletons (Supabase) matching final layout"
loading_states = "Smooth transitions prevent jarring shifts"
realtime = "Direct useUser() hook shows instant email"
professional = "No localStorage lag, immediate auth status"
animation = "Pulse loading matching content dimensions"

[metrics]
# UX quality metrics
loading_time = "< 100ms perceived"
layout_shift = 0
user_feedback = "positive"
accessibility_score = "AA compliant"

[design_system]
components = ["Button", "Card", "Navigation", "Dashboard"]
spacing = ["8px base", "16px standard", "32px section"]
typography = ["Inter font", "14px base", "24px headings"]

# PRODUCTORY BRAND COLORS (LEARNED 2025-08-19)
productory_brand = ["purple-1=#491A73 primary", "purple-2=#830F70 secondary", "purple-3=#B50864 accent", "grey=#475467 text"]
productory_surfaces = ["white=#FFFFFF", "surface-light=#FFFCFE", "surface-tinted=#F6F2F8"]
system_colors = ["success=#16a34a", "warning=#eab308", "destructive=#dc2626"]

# STYLEGUIDE SYSTEM (NEW)
design_tokens = "Tailwind v4 + tokens in documents/core/design/UI_UX_Design_Spec.md"
component_library = "packages/web/src/components/ui/*"

[lessons]
sprint6 = ["Loading skeletons must match final dimensions", "FOUC destroys trust"]
sprint5 = ["Prototype UI not acceptable for production", "Consistency > features"]

[tools]
design = ["figma", "tailwind", "radix-ui"]
testing = ["lighthouse", "axe-core", "percy"]
animation = ["framer-motion", "css-transitions"]
styleguide = "http://localhost:3000/styleguide"

# SPRINT 14 DISCOVERED PATTERNS (2025-08-28)
current_layout = "AppLayout with SidebarProvider + AppSidebar"
header_pattern = "16px height, SidebarTrigger + title + actions"
content_pattern = "flex-1 flex-col gap-4 p-4"
navigation = "Sidebar with collapsible icons, grouped menu items"
card_system = "shadcn Card components with rounded-lg border shadow-sm"

[current_timetables_ui]
# Current placeholder state analyzed
status = "placeholder with 'under development' message"
layout = "centered card with Calendar icon + description"
issues = ["Back to Dashboard button unwanted", "no actual data display", "generic placeholder"]
components_used = ["AppLayout", "Card", "Button", "Calendar icon"]

[data_structure]
# From shared types analysis
presentation_fields = ["id", "title", "url", "total_slides", "created_at", "updated_at"]
timetable_fields = ["startTime", "items", "totalDuration"]
timetable_item_fields = ["id", "title", "content", "startTime", "duration", "endTime"]

[next]
tasks = ["Design timetable card grid layout", "Create loading skeletons", "Design empty states", "Remove Back to Dashboard button"]
priority = "Transform placeholder into functional timetables management interface"
sprint = "14 - Timetables View Implementation"
